name: QA Check

on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # Step 4: Validate Composer files
      - name: Validate Composer files
        run: composer validate --strict

      # Step 5: Run PHPUnit with coverage
      - name: Run Tests with Coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      # Step 6: SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # GitHub auto-provided token
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     # Your SonarCloud token
