name: QA Check

# Trigger the workflow on pull requests targeting the main branch
on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP (adjust version if needed)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Step 3: Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      # Step 4: Run QA checks (for example: Composer validation)
      - name: Validate Composer files
        run: composer validate --strict

      # Optional Step 5: Run PHPUnit tests if applicable
      - name: Run Tests
        run: vendor/bin/phpunit --colors=always
