name: QA Check

on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up PHP
      # Step 0: Clean workspace to remove any cached files
      - name: Clean workspace
        run: git clean -fdx

      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
        
      # Composer validation
      - name: Validate Composer files
        run: composer validate --strict

      # Run PHPUnit tests
      - name: Run Tests
        run: vendor/bin/phpunit --colors=always

      # Run SonarQube scan
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          organization: ${{ secrets.SONAR_ORGANIZATION }}
          token: ${{ secrets.SONAR_TOKEN }}

      # Step 4: Validate Composer files
      - name: Validate Composer files
        run: composer validate --strict

      # Step 5: Create logs folder
      - name: Create logs folder
        run: mkdir -p build/logs

      # Step 6: Run Tests with Coverage
      - name: Run Tests with Coverage
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      # Step 7: SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: Joao-CB_Gondwana_P
          SONAR_ORGANIZATION: Joao-CB

